# (0) Intro on how to do Math with Python

## MPI FKF study group

There is no data analysis and hence machine learning without mathematics. This notebook gives a brief introduction on some of the ways math can be done in Python. The approach is a practical one and is of course not capable of capturing the full abstract nature of a mathermatical concept. A better name for the notebook might be *Calculating Values using Different Mathematical Operations in Python*.

Particularly important are the notations for linear algebra operations as these will later be used in handling data and running our code. If you think of your data stored in a 1D array - a 1D catalog of values in broad terms - then this array can be interpreted as an vector. Multidimensional data can be stored in a matrix, a 2D array, or tensors of higher rank. Python offers efficient ways to do calculations with matrices, vector operations, etc.

We can start start with the simplest operation, addition, $a+b$, <br>
for example <code>2+3</code> 

In [1]:
2+3

5

same for subtraction $a-b$, <br>
<code>2-3</code> <br>
multiplication $a*b$ <br>
<code>2*3</code> <br>
and division $\frac{a}{b}$ <br>
<code>2/3</code>

In [2]:
2-3

-1

In [3]:
2*3

6

In [4]:
2/3

0.6666666666666666

The package [*NumPy*](https://numpy.org/) is a powerful Python package for scientific computing and includes more advanced mathematical operations like the exponental function and square root.<br>

$e^{(a+b)}$ <br>
<code>np.exp(2+3)</code> <br>
$\sqrt{a+b}$<br>
<code>np.sqrt(2+3)</code>

In [5]:
#first the NumPy package needs to be loaded with the following line of code
#numpy is abbreviated as np, this is common practice that you will often see in other people's code

import numpy as np

np.exp(2+3)

148.4131591025766

In [6]:
np.sqrt(2+3)

2.23606797749979

Later we will use tensors. A tensor is, in probably oversimplified terms, a generalized concept of matrix and vector. <br>
A 0D tensor is a number. <br>
A 1D tensor is a vector. <br>
A 2D tensor is a matrix. <br>
etc. <br>
The name *Tensorflow* of Google's framework for machine learning highlights how important the concept of a tensor is. For now let's stick with the names vector and matrix since they are probably more familiar.

A common notation for a vector is $\vec{x}$, for the sake of consistency with many books and online references we will denote this vector as $\mathbf{x}$.

Thus, 
$\mathbf{x} = \left[ \begin{matrix} x_1 \\ \vdots \\ x_n \end{matrix} \right]$ 
is a column vector and
$\mathbf{x} = \left[ \begin{matrix} x_1 && \cdots && x_n \end{matrix} \right]$ 
is a row vector with $n$ entries.

In Python, we can write a vector as an array as

<code>x = [1, 2, 9, 16]</code>

Single elements $x_i$ with index $i$ can be addressed with the pointer $i$. In Python, counting starts with $0$ so that the first, or rather the zeroth element, is called with the index $i=0$, and the third (second) entry with the index $i=2$.

In [7]:
x = [1, 2, 9, 16]
i = 0
print(x[i])

1


In [8]:
i = 2
print(x[i])

9


The same works for matrices with entries $x_{ij}$ in a $n \times m$ matrix with $n$ rows and $m$ columns.

$\mathbf{x} = \left[ \begin{matrix} x_{11} && \cdots && x_{1m} \\ \vdots && \ddots && \vdots \\ x_{n1} && \cdots && x_{nm}\end{matrix} \right]$ 

In [9]:
#matrix with four columns and two rows
x = [ [1, 2, 9, 16], [10, 20, 30, 40] ]

i = 0
j = 3

print(x[i][j]) #value is 16
print(x[1][1]) #value is 20

16
20


With *NumPy* it is easy to sum all entries in a vector by using the built-in function **sum()**.

$$\sum_{i=1}^n x_i$$

<code>np.sum(x)</code>

In [10]:
x = [1, 2, 9, 16]
np.sum(x)

28

This works also for matrices and other mulitdimensional tensors.

In [11]:
x = [ [1, 2, 9, 16], [10, 20, 30, 40] ]
np.sum(x)

128

Another useful property of a tensor is its number of elements. This can be calculated with the function **len()**.

This only works for vectors (1D tensors). For a matrix (2D vector), the returned value is the number of entries in the array. Since a matrix is an array of arrays, it returns the number of arrays stored in the parent array.

In [12]:
x = [1, 2, 9, 16]
y = [ [1, 2, 9, 16], [10, 20, 30, 40] ]

print(len(x))
print(len(y))

4
2


With these two functions it is now easy to calculate the average (mean) of the entries in a vector

$$\frac{1}{n}\sum_{i=1}^n x_i$$

as <code>np.sum(x) / len(x)</code> 

or you can use the built-in function **average()** for this.

<code>np.average(x)</code>

In [13]:
print(np.sum(x) / len(x))
print(np.average(x))

7.0
7.0


Then of course the Euclidean norm (or L2-norm) is a useful measure to characterize a vector.

$\Vert x\Vert_2 = \sqrt{\sum_{i=1}^n x_i^2}$

The Euclidian norm and many other norms of a vector or a matrix can be calculated using the [**numpy.linal.norm** function](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html)

A vector is then easily normlized by deviding each vector element by the norm:

<code>x / LA.norm(x)</code>

In [14]:
#the linalg modul needs to be imported first, abbreviated as LA

from numpy import linalg as LA

print(LA.norm(x))
print(x / LA.norm(x))

18.49324200890693
[0.05407381 0.10814761 0.48666426 0.86518091]


Note in the previous normalization how Python divides, and the same way multiplies, each entry of a vector (array) by a numer by using the code

<code>a*x</code>

which corresponds to the scalar multiplication

$a\mathbf{x}$

This works the same way for matrices.

In [15]:
2*np.array(y)

#I'm not sure here why the array y has to be specified explicitly as a numpy array.
#Not doing this doubles the array, i.e. duplicates entries and makes the array twice as long. Try it out.

array([[ 2,  4, 18, 32],
       [20, 40, 60, 80]])

Addition of a constant to a vector/matrix works equally well.

The mismatch in shapes between the matrix $\mathbf{x}$ and the scalar $2$ is automatically captured by Python in a process called [broadcasting](https://docs.scipy.org/doc/numpy/user/basics.broadcasting.html). Shapes are adjusted such that the arithmetic operation becomes feasible.

In <code>np.array(x)+2</code> the $2$ is broadcasted into a $4 \times 1$ vector with all entries equal $2$.

$\mathbf{x} + c$ becoms 
$$\left[ \begin{matrix} x_1 \\ \vdots \\ x_n \end{matrix} \right] + \left[ \begin{matrix} c \\ \vdots \\ c \end{matrix} \right] = \left[ \begin{matrix} x_1+c \\ \vdots \\ x_n+c \end{matrix} \right]$$

In [16]:
np.array(x)+2

array([ 3,  4, 11, 18])

Further vector operations include the dot product between two vectors $\mathbf{x_1}$ and $\mathbf{x_2}$, which returns a scalar value

$\mathbf{x} \cdot \mathbf{y} = \sum_{i=1}^n x_iy_i$

as <code>np.dot(x,y)</code>

and the Hadamard product (element-wise product), which returns another vector (matrix)

$\mathbf{x} \circ \mathbf{y} = \left[ \begin{matrix} x_{11} \cdot y_{11} && \cdots && x_{1m} \cdot y_{1m} \\ \vdots && \ddots && \vdots \\ x_{n1} \cdot y_{n1} && \cdots && x_{nm} \cdot y_{nm}\end{matrix} \right]$

using **multiply()**

<code>np.multiply(x,y)</code>

In [17]:
x = [1, 2, 9, 16]
y = [1, 2, 3, 4]

print(np.dot(x, y))
print(np.multiply(x, y))

96
[ 1  4 27 64]


The Hadamard product also works for matrices and tensors of higher rank.

In [18]:
x_2D = [ [1, 2, 3], [1, 1, 1] ]
y_2D = [ [1, 2, 9], [2, 4, 18] ]

np.multiply(x_2D, y_2D)

array([[ 1,  4, 27],
       [ 2,  4, 18]])

Element-wise addition works with **np.add()** on vectors and matrices.

In [19]:
print(np.add(x, y))
print(np.add(x_2D, y_2D))

[ 2  4 12 20]
[[ 2  4 12]
 [ 3  5 19]]


The dot product can be used to multiply a matrix with a vector.

$$ \mathbf{x} \cdot \mathbf{w} = \left[ \begin{matrix} x_{11} && \cdots && x_{1m} \\ \vdots && \ddots && \vdots \\ x_{n1} && \cdots && x_{nm}\end{matrix} \right] \left[ \begin{matrix} w_1 \\ \vdots \\ w_m \end{matrix} \right] = \left[ \begin{matrix} \sum_{i=1}^m x_{1i}w_{i} \\ \vdots \\ \sum_{i=1}^m x_{ni}w_{i} \end{matrix} \right] $$

In [20]:
w = [1, 2, 3]

np.dot(x_2D, w)

array([14,  6])

There are many other built-in functions available in Python and particularly in *NumPy*.

But you can also define your own functions in Python $f:X \to Y$, i.e. $y=f(x)$. This is done using the **def** keyword.

<code>def my_function(x):
    y = ...
    return y</code>
    
For example, we can define a function that returns the squared sine of the argument $x$.

In [21]:
def squared_sine(x):
    y = (np.sin(x))*(np.sin(x))
    return y


squared_sine(0.3)

0.08733219254516084